{
 "title": "RocketChat DB",
 "description": "RocketChat DataBase Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Users Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Local Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "Total_Online_Users:",
     "legendFormat": "Online Users",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "Total_Away_Users:",
     "legendFormat": "Idle Users",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "Total_Offline_Users:",
     "legendFormat": "Offline Users",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Abuse App Users",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "Total_Abuse_APP_Tokens:",
     "legendFormat": "Abuse App Users",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Count Total",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "Total_Sent_Messages:",
     "legendFormat": "Sent Messages",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    { "expr": "Total_Uploaded_Documents:", "legendFormat": "Uploaded Attachedments" }
   ]
  },
  {
   "title": "Users Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "Total_Online_Users:", "legendFormat": "Online Users" },
    { "expr": "Total_Away_Users:", "legendFormat": "Idle Users" },
    { "expr": "Total_Busy_Users:", "legendFormat": "Busy Users" }
   ]
  },
  {
   "title": "SentMsg & Attachments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(Total_Sent_Messages:[1h:1m])",
     "legendFormat": "Sent Messages"
    },
    {
     "expr": "delta(Total_Uploaded_Documents:[1h:1m])",
     "legendFormat": "Uploaded Documents"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Cpu Usage DB1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100 )",
     "legendFormat": "Average utilization of Processors",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cpu Usage DB2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100 )",
     "legendFormat": "Average utilization of Processors",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cpu Usage DB3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100 )",
     "legendFormat": "Average utilization of Processors",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Disk Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk IO DB1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\"}[15m]) / 1024",
     "legendFormat": "Total read / kbytes",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[15m]) / 1024",
     "legendFormat": "Total written / kbytes",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk IO DB2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\"}[15m]) / 1024",
     "legendFormat": "Total read / kbytes",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[15m]) / 1024",
     "legendFormat": "Total written / kbytes",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk IO DB3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\"}[15m]) / 1024",
     "legendFormat": "Total read / kbytes",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[15m]) / 1024",
     "legendFormat": "Total written / kbytes",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Network DB1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "KBs", "label": "kilobytes/sec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_network_receive_bytes_total{device=\"ens160\"}[15m]) / 1024",
     "legendFormat": "Network recieved",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens160\"}[15m]) / 1024",
     "legendFormat": "Network transmit",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network DB2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "KBs", "label": "kilobytes/sec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_network_receive_bytes_total{device=\"ens160\"}[15m]) / 1024",
     "legendFormat": "Network recieved",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens160\"}[15m]) / 1024",
     "legendFormat": "Network transmit",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network DB3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "KBs", "label": "kilobytes/sec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_network_receive_bytes_total{device=\"ens192\"}[15m]) / 1024",
     "legendFormat": "Network recieved",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens192\"}[15m]) / 1024",
     "legendFormat": "Network transmit",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DB Cached Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB1",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "node_memory_Cached_bytes",
       "legendFormat": "Cached memory",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "DB2",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "node_memory_Cached_bytes",
       "legendFormat": "Cached memory",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "DB3",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "node_memory_Cached_bytes",
       "legendFormat": "Cached memory",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}